version: "3.8"

services:
  nginx:
    build:
      context: ./nginx
    container_name: nginx
    restart: always
    ports:
      - "80:80"
    depends_on:
      - app
    networks:
      - my-network
      
  app:
    build:
      context: ./app
    container_name: app
    depends_on:
      - database
    networks:
      - my-network

  database:
    image: mysql:5.7
    container_name: database
    restart: always
    command: --innodb-use-native-aio=0
    volumes: 
      - ./database/migrations:/docker-entrypoint-initdb.d/
    ports:
      - 3306:3306
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - my-network

networks:
  my-network:
    driver: bridge